ARG ELK_VERSION

# https://github.com/elastic/beats/tree/master/metricbeat
FROM docker.elastic.co/beats/metricbeat:${ELK_VERSION}

# Add your logstash plugins setup here
# RUN logstash-plugin install logstash-input-stomp
